issues:
  max-per-linter: 0
  max-same-issues: 0

# https://golangci-lint.run/usage/linters/#gocritic
linters:
  disable-all: true
  enable:
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
    disabled-tags:
      - style
      - performance
      - experimental
      - opinionated

run:
  timeout: 10m
  go: 1.18
  skip-dirs:
    - .ci/providerlint/vendor
