issues:
  max-per-linter: 0
  max-same-issues: 0

# From terraform-provider-azurerm
linters:
  disable-all: true
  enable:
    - asciicheck
    - gocritic
    - typecheck
    - vetshadow

run:
  timeout: 75m
  go: 1.18
  skip-dirs:
    - .ci/providerlint/vendor
