issues:
  max-per-linter: 0
  max-same-issues: 0

# https://golangci-lint.run/usage/linters/#errorlint
linters:
  disable-all: true
  enable:
    - errorlint

run:
  timeout: 10m
  go: 1.18
  skip-dirs:
    - .ci/providerlint/vendor
