version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
  settings:
    copyloopvar:
      check-alias: true
    dogsled:
      max-blank-identifiers: 3
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).SetNewComputed
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceDiff).ForceNew
        - io:Close
    errorlint:
      errorf: false
issues:
  max-issues-per-linter: 10
  max-same-issues: 3

run:
  timeout: 75m
