issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errname
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - dogsled
    - errname
    - goconst

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  goconst:
    ignore-tests: true
    min-occurrences: 4

run:
  timeout: 75m
