issues:
  exclude-rules:
    - linters:
        - paralleltest
      # TODO For TestAccXYZ_serial, I *think* we can add t.Parallel() at the top level.
      text: "(Function|Range statement for test) TestAcc"
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - durationcheck
    - paralleltest
    - predeclared
    - tenv
    - tparallel

linters-settings:
  predeclared:
    ignore: cap,close,copy,delete,len,new

run:
  timeout: 75m
  skip-dirs:
    - .ci/providerlint/vendor
