version: "2"
linters:
  default: none
  enable:
    - goconst
    - gocritic
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - staticcheck
  settings:
    goconst:
      min-occurrences: 6
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-tags:
        - experimental
        - opinionated
        - performance
        - style
    mnd:
      checks:
        - argument
      ignored-functions:
        - aws.Int32
        - aws.Int64
        - request.ConstantWaiterDelay
        - request.WithWaiterMaxAttempts
        - nullable.*
        - tfresource.Retry*
        - tfresource.With*
        - retry.RetryContext
        - schema.DefaultTimeout
        - validation.*
        - floatBetweenSchema
        - intBetweenSchema
        - stringLenBetweenSchema
        - int32validator.*
        - int64validator.*
        - listvalidator.*
        - mapvalidator.*
        - setvalidator.*
        - stringvalidator.*
        - SetDefaultCreateTimeout
        - SetDefaultReadTimeout
        - SetDefaultUpdateTimeout
        - SetDefaultDeleteTimeout
        - make
        - strconv.FormatFloat
        - strconv.FormatInt
        - strconv.ParseFloat
        - strconv.ParseInt
        - strings.SplitN
issues:
  max-issues-per-linter: 10
  max-same-issues: 3
formatters:
  enable:
    - gofmt
run:
  timeout: 75m
