name: Acceptance Test Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/acctest-terraform-lint.yml
      - .go-version
      - .ci/.tflint.hcl
      - 'internal/service/**/*_test.go'
      - .ci/scripts/validate-terraform.sh
      - tools/go.mod

env:
  TEST_FILES_PARTITION1: '\./internal/service/[a-d].*/.*_test\.go'
  TEST_FILES_PARTITION2: '\./internal/service/[e-g].*/.*_test\.go'
  TEST_FILES_PARTITION3: '\./internal/service/[h-q].*/.*_test\.go'
  TEST_FILES_PARTITION4: '\./internal/service/[r-z].*/.*_test\.go'

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}

      - run: cd .ci/tools && go install github.com/katbyte/terrafmt

      - run: |
          find ./internal/service -type f -name '*_test.go' \
            | sort -u \
            | xargs -I {} terrafmt diff --check --fmtcompat {}

  validate-testsa:
    name: Validate Tests 1 of 4
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}
      - run: tflint -c .ci/.tflint.hcl --init
      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION1 }} | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION1 }} \
            | .ci/scripts/validate-terraform.sh
  validate-testsb:
    name: Validate Tests 2 of 4
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}
      - run: tflint -c .ci/.tflint.hcl --init
      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION2 }} | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION2 }} \
            | .ci/scripts/validate-terraform.sh
  validate-testsc:
    name: Validate Tests 3 of 4
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}
      - run: tflint -c .ci/.tflint.hcl --init
      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION3 }} | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION3 }} \
            | .ci/scripts/validate-terraform.sh
  validate-testsd:
    name: Validate Tests 4 of 4
    runs-on: [custom, linux, small]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - uses: actions/cache@v3
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/katbyte/terrafmt
      - run: cd .ci/tools && go install github.com/terraform-linters/tflint
      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.ci/.tflint.hcl') }}
      - run: tflint -c .ci/.tflint.hcl --init
      - run: echo -n "File count $( find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION4 }} | xargs )"
      - run: |
          find ./internal -type f -regextype egrep -regex ${{ env.TEST_FILES_PARTITION4 }} \
            | .ci/scripts/validate-terraform.sh