name: Autoremove Labels
on:
  issues:
    types: [closed, opened]
  pull_request_target:
    types: [closed]
jobs:
  RemoveNeedsTriageFromMembers:
    if: github.event.action == 'opened'
    env:
      ALLOW_LISTED: ${{ contains(fromJSON('["anGie44", "bflad", "breathingdust", "ewbankkit", "gdavison", "johnsonaj", "justinretzolk", "maryelizbeth", "YakDriver", "zhelding"]'), github.actor) }}
      HAS_NEEDS_TRIAGE: ${{ contains(github.event.*.labels.*.name, 'needs-triage') }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-triage label from member's Issues
        if: ${{ env.ALLOW_LISTED == 'true' }} && ${{ env.HAS_NEEDS_TRIAGE == 'true' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'needs-triage'
  RemoveTriageLabelsFromClosed:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        labels: ['needs-triage', 'waiting-response']
    steps:
      - name: Remove ${{ matrix.labels }} label
        uses: actions-ecosystem/action-remove-labels@v1
        if: contains(github.event.*.labels.*.name, matrix.labels)
        with:
          labels: ${{ matrix.labels }}
