name: Post Publish
on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        description: 'Semver release tag e.g. v1.1.0'
        required: true
  workflow_run:
    workflows: [Release]
    types:
      - completed
jobs:
  on-success-or-workflow-dispatch:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    outputs:
      release-tag: ${{ steps.release-tag.outputs.tag }}
    steps:
      - if: github.event_name == 'workflow_run'
        name: Download Artifact from Release workflow
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
          workflow: release.yml
          name: release-tag
      - name: Output Release Tag
        id: release-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag=${{ github.event.inputs.release-tag }}" >> "$GITHUB_OUTPUT"
          else
            value=`cat release-tag.data`
            echo "tag=$value" >> "$GITHUB_OUTPUT"
          fi
  tidy-jira:
    needs: [on-success-or-workflow-dispatch]
    runs-on: ubuntu-latest
    steps:
      - name: Tidy Jira
        uses: breathingdust/github-jira-tidy@b503407f09af5564fd806924bdf4495510d848b6 # v0.10.0
        with:
          jira_host: 'hashicorp.atlassian.net'
          jira_username: 'sdavis@hashicorp.com'
          jira_password: ${{ secrets.jira_password }}
          jira_jql_filter: ${{ secrets.jira_jql_filter }}
          jira_github_url_field_id: 'cf[10089]'
          github_release_name: ${{ needs.on-success-or-workflow-dispatch.outputs.release-tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  registry-check:
    runs-on: ubuntu-latest
    needs: [on-success-or-workflow-dispatch]
    steps:
      - name: Registry Version Check
        id: registry_latest_ver
        shell: bash
        run: |
          LATEST_VERSION=$(curl -s "https://registry.terraform.io/v2/providers/323/provider-versions/latest" | jq -r '.data.attributes.version')
          if [[ " ${{ needs.on-success-or-workflow-dispatch.outputs.release-tag }}" != ${LATEST_VERSION} ]]; then
            case "$OSTYPE" in
              darwin*) sleep 1h ;;
              linux*) sleep 1h ;;
              msys*) Start-Sleep -s 3600
              *) echo "unknown: $OSTYPE" ;;
            esac
          else
            echo "Registry and Github Version matches"
          fi

  os-version-init:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run Terraform Init on the os-version-init
        run: |
          echo "Setting provider version in Terraform configuration..."
          cat <<EOF > main.tf
          terraform {
            required_providers {
              aws = {
                source  = "${PROVIDER}"
                version = ${LATEST_VERSION}
              }
            }
          }

          provider "aws" {
            region = "us-east-1"
          }
          EOF


          echo "Terraform configuration file (main.tf) created with the latest version."

          echo "Initializing Terraform with the latest AWS provider..."
          terraform init -upgrade

          if [ $? -ne 0 ]; then
            echo "Terraform initialization failed."
            exit 1
          fi

  on-version-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() && (needs.os-version-init.result == 'failure') }}
    needs:
      [os-version-init]
    steps:
      - uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ${{ toJSON(format('ERROR; Registry Terraform Provider Initiation Failed')) }}
                  }
                }
              ]
            }
