name: 'Modify Issue or Pull Request Labels'

on:
  workflow_call:
    inputs:
      add:
        description: '(Optional) The comma-separated label(s) to add to the Issue or Pull Request.'
        required: false
        type: string
      remove:
        description: '(Optional) The comma-separated label(s) to remove from the Issue or Pull Request.'
        required: false
        type: string

env:
  GH_TOKEN: ${{ github.token }}
  ITEM_URL: ${{ github.event.issue.html_url || github.event.pull_request.html_url }}

jobs:
  modify-labels:
    name: 'Modify Label(s)'
    runs-on: ubuntu-latest
    env:
      ITEM_TYPE: 'pr'
    steps:
      - name: 'Determine if the Item is an Issue or Pull Request'
        if: github.event_name == 'issues'
        run: |
          echo 'ITEM_TYPE=issue' >> $GITHUB_ENV

      - name: 'Add Label(s) to Issue or Pull Request'
        if: inputs.add != ''
        run: |
          gh $ITEM_TYPE edit $ITEM_URL --add-label ${{ inputs.add }}

      - name: 'Remove Label(s) From Issue or Pull Request'
        if: inputs.remove != ''
        run: |
          gh $ITEM_TYPE edit $ITEM_URL --remove-label ${{ inputs.remove }}
