name: team-slack-bot

on:
  schedule:
    - cron: '0 15 * * 1-5'

jobs:
  open-pr-stats:
    runs-on: ubuntu-latest
    name: open-pr-stats
    if: github.repository_owner == 'hashicorp'
    steps:
      - name: open-pr-stats
        uses: breathingdust/github-team-slackbot@78d75b2779c6c42f812c5dd0709bb0874f7002b0
        with:
          github_token: ${{ secrets.ORGSCOPED_GITHUB_TOKEN}}
          org: hashicorp
          repo: terraform-provider-aws
          team_slug: terraform-aws
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel: ${{ secrets.SLACK_CHANNEL }}
